### PR TITLE
fix: normalize slashes

### PR DESCRIPTION
**Pull request by antfu**

### CODE REVIEW

**Comment by JohnCampionJr** [comment]
I'll try it now

**Comment by JohnCampionJr** [comment]
Initial load works, HMR does not.

**Comment by JohnCampionJr** [comment]
I've got to run out.   This change fixes it in matchGlobs in utils.ts

The absolute path in the path returned and the relative path in the glob seem to cause a mismatch in minimatch.

Context.ts
```ts
matchGlobs(path, globs, this.viteConfig.root)
```

Utils.ts
```ts
  const relative = slash(filepath).replace(root + '/', "")
  for (const glob of globs) {
    if (minimatch(slash(relative), glob))
```

**Comment by hannoeru** [comment]
@JohnCampionJr @antfu 
That should fixed all the problems,
include HMR and resolve the correct component name.
Tested in Windows 10.

**Comment by antfu** [comment]
Thank you Han!

**Comment by JohnCampionJr** [comment]
Yup,  confirmed here too.  Thanks!!

**Pull request merged**
